---

version: 0.0
os: linux

files:
  - source: ./render
    destination: /opt/wcaas/www/clarogt-DEPLOY

permissions:
  - object: /opt/wcaas/www/clarogt-DEPLOY
    owner: wcaas
    group: wcaas
    mode: 644
    type:
      - file
  - object: /opt/wcaas/www/clarogt-DEPLOY
    owner: wcaas
    group: wcaas
    mode: 755
    type:
      - directory
  - object: /opt/wcaas/www
    pattern: clarogt-DEPLOY
    owner: wcaas
    group: wcaas
    mode: 755
    type:
      - directory

hooks:
  AfterInstall:
    - location: /scripts/render_after_install
      timeout: 10
