image:
  name: docker.edgebound.net/wcaas/node-builder:latest
  username: $APOTHECA_USERNAME
  password: $APOTHECA_PASSWORD

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - npm install
          - mkdir -p target/codedeploy/render/QA target/codedeploy/render/PROD target/codedeploy/render/UAT target/codedeploy/scripts
          - cp .env-QA .env
          - NODE_ENV=QA npm run build
          - cp -pr public/* target/codedeploy/render/QA/
          - cp .env-UAT .env
          - NODE_ENV=UAT npm run build
          - cp -pr public/* target/codedeploy/render/UAT/
          - cp .env-PROD .env
          - NODE_ENV=PROD npm run build
          - cp -pr public/* target/codedeploy/render/PROD/
          - cp /opt/wcaas/bin/* target/codedeploy/scripts/
          - cp appspec.yml target/codedeploy/appspec.yml
          - cd target/codedeploy
          - tar -cvzf ../render.tar.gz *
          - aws s3 cp ../render.tar.gz s3://wcaas-deployments/
