const fakeListGiro = [{
  id_giro: 'AGRICULTURA, GANADERÍA, SILVICULTURA Y PESCA',
  giro_name: 'AGRICULTURA, GANADERÍA, SILVICULTURA Y PESCA',
},
{
  id_giro: 'EXPLOTACIÓN DE MINAS Y CANTERAS',
  giro_name: 'EXPLOTACIÓN DE MINAS Y CANTERAS',
}, {
  id_giro: 'INDUSTRIAS MANUFACTURERAS',
  giro_name: 'INDUSTRIAS MANUFACTURERAS',
}, {
  id_giro: 'SUMINISTROS DE ELECTRICIDAD, GAS, VAPOR Y AIRE ACONDICIONADO',
  giro_name: 'SUMINISTROS DE ELECTRICIDAD, GAS, VAPOR Y AIRE ACONDICIONADO',
}, {
  id_giro: 'SUMINISTRO DE AGUA, EVACUACIÓN DE AGUAS RESIDUALES (ALCANTARILLADO); GESTIÓN DE DESECHOS Y ACTIVIDADES DE SANEAMIENTO',
  giro_name: 'SUMINISTRO DE AGUA, EVACUACIÓN DE AGUAS RESIDUALES (ALCANTARILLADO); GESTIÓN DE DESECHOS Y ACTIVIDADES DE SANEAMIENTO',
}, {
  id_giro: 'CONSTRUCCIÓN',
  giro_name: 'CONSTRUCCIÓN',
}, {
  id_giro: 'COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS',
  giro_name: 'COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS',
}, {
  id_giro: 'TRANSPORTE Y ALMACENAMIENTO',
  giro_name: 'TRANSPORTE Y ALMACENAMIENTO',
}, {
  id_giro: 'ALOJAMIENTO Y SERVICIOS DE COMIDA',
  giro_name: 'ALOJAMIENTO Y SERVICIOS DE COMIDA',
}, {
  id_giro: 'INFORMACIÓN Y COMUNICACIONES',
  giro_name: 'INFORMACIÓN Y COMUNICACIONES',
}, {
  id_giro: 'ACTIVIDADES FINANCIERAS Y DE SEGUROS',
  giro_name: 'ACTIVIDADES FINANCIERAS Y DE SEGUROS',
}, {
  id_giro: 'ACTIVIDADES INMOBILIARIAS',
  giro_name: 'ACTIVIDADES INMOBILIARIAS',
}, {
  id_giro: 'ACTIVIDADES DE SERVICIOS PROFESIONALES, CIENTÍFICOS Y TÉCNICOS',
  giro_name: 'ACTIVIDADES DE SERVICIOS PROFESIONALES, CIENTÍFICOS Y TÉCNICOS',
}, {
  id_giro: 'ACTIVIDADES ADMINISTRATIVAS Y SERVICIOS DE APOYO',
  giro_name: 'ACTIVIDADES ADMINISTRATIVAS Y SERVICIOS DE APOYO',
}, {
  id_giro: 'ADMINISTRACIÓN PÚBLICA Y DEFENSA; PLANES DE SEGURIDAD SOCIAL DE AFILIACIÓN OBLIGATORIA',
  giro_name: 'ADMINISTRACIÓN PÚBLICA Y DEFENSA; PLANES DE SEGURIDAD SOCIAL DE AFILIACIÓN OBLIGATORIA',
}, {
  id_giro: 'ENSEÑANZA',
  giro_name: 'ENSEÑANZA',
}, {
  id_giro: 'SERVICIOS SOCIALES  Y RELACIONADO CON LA SALUD HUMANA',
  giro_name: 'SERVICIOS SOCIALES  Y RELACIONADO CON LA SALUD HUMANA',
}, {
  id_giro: 'ARTE, ESPARCIMIENTO Y OCIO',
  giro_name: 'ARTE, ESPARCIMIENTO Y OCIO',
}, {
  id_giro: 'ACTIVIDADES DE SERVICIOS NCP',
  giro_name: 'ACTIVIDADES DE SERVICIOS NCP',
}, {
  id_giro: 'ACTIVIDADES DE LOS HOGARES EN CALIDAD DE EMPLEADORES, ACTIVIDADES INDIFERENCIADAS DE PRODUCCIÓN DE BIENES Y SERVICIOS DE LOS HOGARES PARA USO PROPIO',
  giro_name: 'ACTIVIDADES DE LOS HOGARES EN CALIDAD DE EMPLEADORES, ACTIVIDADES INDIFERENCIADAS DE PRODUCCIÓN DE BIENES Y SERVICIOS DE LOS HOGARES PARA USO PROPIO',
}, {
  id_giro: 'ACTIVIDADES DE ORGANIZACIONES Y ÓRGANOS EXTRATERRITORIALES',
  giro_name: 'ACTIVIDADES DE ORGANIZACIONES Y ÓRGANOS EXTRATERRITORIALES',
}];

export default fakeListGiro;
