import React from 'react';
import { Helmet } from 'react-helmet';

const Terms = () => {
  const tableStyle = {
    width: '80%',
    borderCollapse: 'collapse',
    border: 'solid',
    borderWidth: '1px'
  };

  const trStyle = {
    borderCollapse: 'collapse',
    border: 'solid',
    borderWidth: '1px'
  }

  const tdStyle = {
    borderCollapse: 'collapse',
    border: 'solid',
    borderWidth: '1px'
  }

  const h4Underline = {
    textDecoration: 'underline'
  }

  return (
    <main>
      <Helmet title={`Términos y Condiciones | Gummybears ${process.env.COUNTRY}`} />
      <section className="static--terms">
        <h1>TÉRMINOS Y CONDICIONES DE USO DEL SITIO “---”</h1>
        <p>Los presentes términos y condiciones generales de uso (en adelante los “Términos y Condiciones”) serán los aplicables a las compras de <strong>productos y servicios de telefonía</strong>  que al efecto sean <strong>ofrecidos</strong> por Gummybears, constituida bajo las leyes de la Republica de Guatemala, con Número de Identificación Tributaria 0614-261098-101-2, con domicilio social en San Salvador, (EN ADELANTE “Gummybears”) a través del sitio web <strong>uat-gummybears.com</strong>.</p>
        <p>CUALQUIER PERSONA QUE DESEE ACCEDER Y/O USAR EL SITIO WEB PARA COMPRAR PRODUCTOS Y SERVICIOS DE TELEFONÍA (INICIALMENTE TELÉFONOS Y/O SERVICIOS MÓVILES PREPAGO), PODRÁ HACERLO ACEPTANDO Y SUJETÁNDOSE A LOS PRESENTES TÉRMINOS Y CONDICIONES GENERALES, LOS CUALES TIENEN UN CARÁCTER OBLIGATORIO Y VINCULANTE. AL USAR EL SITIO, EL USUARIO ACEPTA ESTOS TÉRMINOS Y CONDICIONES Y CUMPLIR CON LOS MISMOS, POR LO QUE LE PEDIMOS DEDIQUE UNOS MINUTOS PARA REVISARLOS CUIDADOSAMENTE. SI NO ESTÁ DE ACUERDO, O NO ACEPTA LOS MISMOS, DEBERÁ ABSTENERSE DE UTILIZAR EL SITIO Y/O LOS SERVICIOS. AL USAR EL SITIO uat-gummybears.com SE ENTENDERÁ COMO EL TOTAL CONSENTIMIENTO DEL USUARIO A ESTOS TÉRMINOS Y CONDICIONES.</p>
        <p>El Usuario debe leer, entender y aceptar todas las condiciones establecidas en los Términos y Condiciones Generales y en las Políticas de Privacidad, así como en los demás documentos incorporados a los mismos por referencia, previos a su registro como Usuario de uat-gummybears.com.</p>
        <h3>Capacidad Jurídica</h3>
        <p>Los productos y servicios de telefonía que ofrece el sitio uat-gummybears.com, está reservado y dirigido únicamente para personas que tengan capacidad legal para contratar. Queda bajo responsabilidad del Usuario que la transacción únicamente sea realizada por el titular del medio de pago, por lo que los padres o tutores, son responsables de supervisar la conducta de los menores de edad que ingresen al sitio.</p>
        <p>En caso de registrar a una persona jurídica como usuario, se deberá contar con la capacidad jurídica para contratar y obligarse en los términos de estos Términos y Condiciones.</p>
        <h2>A. CONDICIONES DE ACCESO Y CONTENIDO</h2>
        <h3>i. Registro de Usuario.</h3>
        <p>Gummybears requiere que el usuario se registre para acceder al sitio web y haga uso de uat-gummybears.com por lo que es obligatorio completar el formulario de registro en todos sus campos con datos válidos para poder utilizar los servicios que brinda uat-gummybears.com, así como el o los domicilios que registre para que se envíen los productos que contrate. El Usuario deberá completarlo con su información personal de manera exacta, precisa y bajo protesta de decir verdad ('Datos Personales') y asume el compromiso de actualizar los Datos Personales conforme resulte necesario.</p>
        <p>Proporcionar cualquier información falsa o inexacta, constituye un incumplimiento a estos TÉRMINOS Y CONDICIONES. Gummybears podrá utilizar diversos medios para identificar a sus Usuarios.  Los Usuarios garantizan y responden, en cualquier caso, de la veracidad, exactitud, vigencia y autenticidad de los Datos Personales ingresados.</p>
        <h3>ii. Contraseña.</h3>
        <p>El Usuario proporcionará un correo electrónico para identificar su cuenta (en adelante “Cuenta”), y generará una “Contraseña” para acceder a dicha cuenta, tales elementos fungirán como mecanismo de seguridad para la autenticación del Usuario. </p>
        <p>La Contraseña deberá integrarse con las especificaciones y/o algoritmos que el sistema de la página uat-gummybears.com le indique, la Contraseña será necesaria para que el Usuario pueda acceder a su cuenta.</p>
        <p>El Usuario se obliga a mantener la confidencialidad de su Contraseña. La “Contraseña” podrá ser modificada posteriormente por el Usuario de conformidad con lo previsto en los presentes términos y condiciones.</p>
        <p>El Usuario reconoce el carácter personal e intransferible de la “Contraseña” la cual quedará bajo su custodia, control y cuidado, por lo que será de la exclusiva responsabilidad del Usuario cualquier daño o perjuicio que pudiese sufrir como consecuencia del uso indebido de la misma.</p>
        <h3>iii. Obligaciones del Usuario en el Sitio Web:</h3>
        <p>La Cuenta es personal, única e intransferible, y está prohibido que un mismo Usuario registre o posea más de una Cuenta. En caso que uat-gummybears.com detecte distintas Cuentas que contengan datos coincidentes o relacionados, podrá dar de baja la Cuenta subsiguiente respectiva, previa notificación que haga al Usuario, al domicilio que éste haya registrado en el Portal o a través de correo electrónico a la dirección electrónica que el Usuario haya proporcionado a uat-gummybears.com.</p>
        <p>El Usuario será responsable a título personal por todas las operaciones efectuadas en su Cuenta, pues el acceso a la misma está restringido y el uso de su “Contraseña” es exclusivo del Usuario.</p>
        <p>El Usuario se compromete a notificar a uat-gummybears.com en forma inmediata y por medio idóneo siendo éste el correo electrónico enviado a la cuenta de correo registrada o marcando a los números *85 o +503 2250-5555, cualquier uso no autorizado de su Cuenta, así como el ingreso por terceros no autorizados a la misma. Se aclara que está prohibida la venta, cesión o transferencia de la Cuenta (incluyendo la reputación y calificaciones) bajo ningún título. Gummybears podrá solicitar cualquier información adicional para confirmar la identidad del Usuario.</p>
        <h3>iv. Sanciones y suspensiones al Usuario del sitio web:</h3>
        <p>uat-gummybears.com podrá cancelar o restringir la cuenta de los Usuarios, si detecta algún uso indebido del sitio o de los productos y/o servicios que se ofrecen en el mismo, previa notificación que haga al Usuario, al domicilio que éste haya registrado en el Portal o a través de correo electrónico a la dirección electrónica que el Usuario haya proporcionado a uat-gummybears.com.</p>
        <p>Sin perjuicio de otras medidas, uat-gummybears.com podrá advertir, suspender en forma temporal o inhabilitar definitivamente la Cuenta de un Usuario si: (a) se quebrantara alguna ley, o cualquiera de las estipulaciones de estos Términos y Condiciones Generales y demás políticas de uat-gummybears.com   (b) incumpliera sus obligaciones como Usuario; (c) se incurriera a criterio de uat-gummybears.com en conductas o actos dolosos o fraudulentos; (d) no pudiera verificarse la identidad del Usuario o cualquier información proporcionada por él fuere errónea.</p>
        <p>De darse el caso, uat-gummybears.com notificará al Usuario, al domicilio que éste haya registrado en el Portal o a través de correo electrónico a la dirección electrónica que el Usuario haya proporcionado a uat-gummybears.com, previo a iniciar las acciones que estime pertinentes.</p>
        <p>El Usuario autoriza expresamente a uat-gummybears.com para que pueda confirmar los Datos Personales suministrados, de igual forma uat-gummybears.com, podrá consultar el historial crediticio del Usuario, con las empresas de información crediticia que legalmente operan en Guatemala, para lo cual, el Usuario autorizará de forma expresa a uat-gummybears.com para consultar y/o compartir esos datos, con las mencionadas entidades. La información que uat-gummybears.com obtenga de estas entidades será tratada en forma confidencial.</p>
        <h3>v. Privacidad de la Información</h3>
        <p>Para utilizar el Contenido y los Servicios ofrecidos por uat-gummybears.com, los Usuarios deberán facilitar determinados datos de carácter personal. Su información personal se procesa y almacena en servidores o medios magnéticos que mantienen altos estándares de seguridad y protección tanto física como tecnológica. Para mayor información sobre la privacidad de los Datos Personales y casos en los que será revelada la información personal, el Usuario podrá consultar las Políticas de Privacidad, detalladas en este documento.</p>
        <h3>vi. SERVICIOS DEL SITIO WEB uat-gummybears.com:</h3>
        <p>El acceso y navegación al sitio web: uat-gummybears.com, es de carácter gratuito y ofrece información acerca de los productos y/o servicios comercializados por Gummybears, al hacer el registro e ingreso por medio del sitio web, el usuario puede consultar los productos y/o servicios comprados, hacer pagos aplicables a los productos y/o servicios adquiridos, e información general que se encontrará disponible en el sitio web de Gummybears de forma actualizada.</p>
        <h3>vii. CONTENIDO DEL SITIO WEB uat-gummybears.com:</h3>
        <p>Las imágenes, información, mensajes, gráficos, dibujos, sonidos, imágenes, fotografías, grabaciones, software y, en general, cualquier clase de material accesible a través del sitio web, de los productos publicados en el sitio uat-gummybears.com son proporcionadas por los proveedores o fabricantes de los mismos. La resolución del monitor en el cual el Usuario vea los artículos que se publican en el sitio web uat-gummybears.com, hace imposible que uat-gummybears.com pueda garantizar que el color que el Usuario aprecia en su monitor, coincida exactamente con el color del producto físico.</p>
        <p>El Usuario se compromete a hacer un uso correcto, personal y lícito sobre el contenido del sitio web uat-gummybears.com, por lo que debe abstenerse de reproducir, copiar, distribuir, vender en forma directa con fin comercial, transformar, adaptar, modificar, o permitir cualquier tipo de contenido que posea el sitio web de Gummybears.</p>
        <h2>B. DESCRIPCIÓN OPERATIVA DE LA PLATAFORMA TECNOLÓGICA</h2>
        <p><strong>i. Venta de productos y/o servicios: </strong>En el sitio uat-gummybears.com se publicarán los productos y servicios ofrecidos, así como el precio el cual tendrá incluido IVA y CESC que el Usuario deberá pagar por ellos y los plazos para el pago, entre otros. Los precios de envío y otros se agregarán en el detalle antes de la compra.</p>
        <p><strong>ii. Promociones: </strong>Asimismo, se indicará si se encuentra disponible alguna promoción y/o descuento en la Gummybears, la vigencia de la misma y el número de productos disponibles para la promoción y/o descuento, así como los medios de pago habilitados para efectuar el pago de dichos productos y/o servicios.</p>
        <p><strong>iii. Impuestos: </strong>Tal como lo establece la legislación fiscal vigente, Gummybears emitirá la factura que ampare la compra de los productos  y servicios de telefonía , comprobante que le será entregado al Usuario de manera física al recibir su producto y/o a través de su correo electrónico registrado en uat-gummybears.com.</p>
        <p><strong>iv. Seguimiento de la orden: </strong>En caso de que el Usuario opte por la compra de cualquiera de los <strong>productos y servicios de telefonía</strong>, el número de orden que se asigna al realizar la transacción en el sitio web uat-gummybears.com, servirá al Usuario para dar seguimiento a la compra correspondiente. Si uat-gummybears.com tuviera algún problema con la orden del Usuario, por ejemplo, que no se localice para la entrega de su pedido, se le informará al Usuario vía correo electrónico o vía telefónica, al correo electrónico y teléfonos que haya proporcionado el Usuario al momento de su Registro, procurando en la medida de lo posible resolver el inconveniente. En casos de preventas, el envío se realizará al momento de contar con el producto correspondiente, para lo cual se informará a El Usuario el plazo máximo de entrega del mismo.</p>
        <p><strong>v. Aprobación del pedido: </strong>Gummybears remitirá al Usuario, el detalle de la orden al momento de realizar la compra, y además podrá confirmar telefónicamente con el Usuario las ordenes que éste último haya generado en el sitio web uat-gummybears.com. En caso que el Usuario no reconozca las ordenes, uat-gummybears.com procederá a la cancelación de las mismas. Una vez confirmada la orden por el Usuario, uat-gummybears.com enviará un correo electrónico a la cuenta del Usuario, en el que se detallarán los productos adquiridos, el precio total a pagar, y la forma de pago seleccionada por el Usuario, esto con la finalidad de que el Usuario realice el pago de los productos respectivos.</p>
        <p><strong>vi. Forma de pago: </strong>Gummybears por medio del sitio web: uat-gummybears.com tendrá habilitados como medios de pago las tarjetas de débito y tarjetas de crédito a través de las cuales el Usuario podrá pagar el precio de los productos  y servicios  de telefonía que adquiera a través del sitio web uat-gummybears.com  obligándose el Usuario a pagar el precio de los productos y/o servicios de que se trate, de acuerdo a la forma de pago que elija al momento de concretar la compra del mismo. Si la forma de pago elegida por el usuario para adquirir un producto es por medio de tarjeta de crédito/debito, solo podrá hacer uso ella si su tarjeta es VISA, MASTERCARD o AMERICAN EXPRESS, y uat-gummybears.com no guardará ningún dato de la misma, como nombre, apellido, fecha de vencimiento, código de verificación de tarjeta bancaria, número de tarjeta. El Usuario comprende que, al elegir como forma de pago, una tarjeta de crédito, el acreedor del Usuario, será la institución bancaria que le otorgue el crédito respectivo.</p>
        <p><strong>vii. Envío de la orden: </strong>Gummybears por medio del sitio web: uat-gummybears.com enviará los productos que el Usuario haya adquirido, a través de la empresa de mensajería (courier) autorizada por Gummybears. El costo del envío se indicará en el sitio web uat-gummybears.com junto con el precio del producto correspondiente. Con la finalidad de brindar seguridad al Usuario en la entrega de los productos que adquiera a través del sitio uat-gummybears.com, éste acepta que al recibir el producto deberá presentar una copia de su Documento Único de Identidad (DUI) o pasaporte vigente a la empresa de mensajería que corresponda, para que ésta pueda hacer la entrega del producto correspondiente.</p>
        <p><strong>viii. Recepción del envío: </strong>El usuario comprador podrá especificar en la página uat-gummybears.com si él mismo recibirá el paquete o si autoriza a un tercero a recibirlo por él y siendo el caso, el Usuario deberá indicar el nombre completo y Documento Único de Identidad (DUI) o Pasaporte de la persona que recibirá el producto, debiendo ésta presentar su identificación vigente y en perfecto estado, y firmar una constancia de recibimiento del producto en el momento de entrega. En el supuesto de que no se pueda localizar al Usuario o al tercero designado para entregarle el producto en dos (2) ocasiones, la empresa de mensajería devolverá el producto a uat-gummybears.com y se procederá como se indica en el siguiente párrafo.</p>
        <p><strong>ix. Autorización para recibir productos: </strong>En caso de que el Usuario autorice a un tercero para la recepción de los productos que el Usuario adquiera a través de uat-gummybears.com, se entenderá que el tercero acepta la recepción del producto encomendado por el Usuario, en el entendido que al entregar el producto como el Usuario ha autorizado, el Usuario desvincula a Gummybears de responsabilidad alguna al respecto. Al momento de la recepción, la persona receptora debe entregar la copia del documento de identidad de la persona que realizó la compra a través de uat-gummybears.com, de lo contrario no será entregado el producto.</p>
        <p><strong>x. Entrega no Completada o Rechazada: </strong> Gummybears por medio del sitio web uat-gummybears.com informará al Usuario a través de correo electrónico o llamada telefónica que, luego de dos (2) intentos de entrega, la misma no fue posible o fue rechazada, por lo que notificará vía correo electrónico la fecha a partir de la cual el usuario pueda presentarse a recoger su orden en la bodega central de Gummybears ubicada en Complejo Ex-Incatel, Edif. “A”, 1er. nivel, Carretera a Santa Tecla. Santa Tecla, La Libertad en horarios de atención al público. No se realizarán entregas en días domingo.</p>
        <p><strong>xi. Trámite y Plazo de entrega:</strong> Las órdenes de compra o pedidos son procesadas en menos de 72 horas hábiles. Las órdenes recibidas después de las 16:00 horas, serán procesadas al siguiente día hábil. Si existiese retraso de entrega en el producto, se le estará notificando al Usuario ya sea por medio del tracking en el portal uat-gummybears.com, por correo electrónico, o por llamada telefónica a los números registrados. El Usuario recibirá su producto como máximo de 10 días hábiles en la zona metropolitana y en el interior del país, dependiendo de la ubicación a enviar, dentro del territorio nacional salvadoreño.</p>
        <p><strong>xii. Devolución y Garantía:</strong>La garantía y servicio de reparación de aparatos celulares adquiridos en el sitio web uat-gummybears.com se aplicará de forma directa con Gummybears conforme a sus políticas, procedimientos y restricciones. Para esto el Usuario deberá acudir a cualquiera de los Centros de Atención al Cliente (CAC) o Agencias de Gummybears siguientes, para la evaluación de su equipo:</p>
        <ul className="static--conditions">
          <li><table align="center" style={tableStyle}>
            <tr style={trStyle}><td style={tdStyle}>Agencia Plaza Merliot</td><td style={tdStyle}>Agencia Metro8a etapa SS</td><td style={tdStyle}>Agencia Santa Ana</td></tr>
            <tr style={trStyle}><td style={tdStyle}>Agencia Aguilares</td><td style={tdStyle}>Agencia La Gran vía</td><td style={tdStyle}>Agencia Metro2 Santa Ana</td></tr>
            <tr style={trStyle}><td style={tdStyle}>Agencia Periplaza</td><td style={tdStyle}>Agencia Multiplaza</td><td style={tdStyle}>Agencia Chalatenango</td></tr>
            <tr style={trStyle}><td style={tdStyle}>Agencia MetroSur</td><td style={tdStyle}>Agencia Plaza Merliot</td><td style={tdStyle}>Agencia Acajutla</td></tr>
            <tr style={trStyle}><td style={tdStyle}>Agencia Metro10a etapa SS</td><td style={tdStyle}>Agencia Quezaltepeque</td><td style={tdStyle}>Agencia Metro1 Sonsonate</td></tr>
            <tr style={trStyle}><td style={tdStyle}>Agencia Olímpica</td><td style={tdStyle}>Agencia Unicentro Lourdes</td><td style={tdStyle}>Agencia Sonsonate</td></tr>
            <tr style={trStyle}><td style={tdStyle}>Agencia Plaza Mundo2</td><td style={tdStyle}>Agencia Cojutepeque</td><td style={tdStyle}>Agencia Ahuachapán</td></tr>
            <tr style={trStyle}><td style={tdStyle}>Agencia San Luis</td><td style={tdStyle}>Agencia Zacatecoluca</td><td style={tdStyle}>Agencia Ilobasco</td></tr>
            <tr style={trStyle}><td style={tdStyle}>Agencia Telgrafo</td><td style={tdStyle}>Agencia Chalchuapa</td><td style={tdStyle}>Agencia San Vicente</td></tr>
            <tr style={trStyle}><td style={tdStyle}>Agencia Galerías</td><td style={tdStyle}>Agencia Metapán</td><td style={tdStyle}>Agencia Usulután</td></tr>
            <tr style={trStyle}><td style={tdStyle}>Agencia San Miguel Centro</td><td style={tdStyle}>Agencia San Fco Gotera</td><td style={tdStyle}>Agencia La Unión</td></tr>
            <tr style={trStyle}><td style={tdStyle}>Agencia Santa Rosa de Lima</td><td style={tdStyle}></td><td></td></tr>
          </table></li>
        </ul>
        <p>Para todo trámite, el Usuario debe presentar su Documento de Único de Identidad (DUI o, pasaporte vigente, factura de adquisición del producto e impresión de comprobante de entrega de equipo, el cual se envía por correo electrónico al momento de envío de la orden de compra o pedido.</p>
        <p>Las políticas de garantías y devoluciones aplicables a la compra de teléfonos en modalidad prepago, son las siguientes:</p>
        <ul className="static--conditions">
          <li>
            <p><strong>Garantía de Fábrica</strong>Esta garantía consiste en la reparación o cambio de equipo cuando presente desperfectos de fábrica. El tiempo de garantía que Gummybears ofrece al usuario es de hasta 12 meses, el cual inicia a partir de la fecha de facturación (compra del aparato) y aplica únicamente por desperfectos de fábrica.  Existe una garantía de cambio inmediato dentro de los primeros 7 días de haber recibido el equipo. Para más información leer las políticas de Garantía al final del presente documento.</p>
          </li>
          <li>
            <h3>Devoluciones:</h3>
            <ul className="static--conditions">
              <li><strong>•</strong>  La devolución por inconformidad del equipo debe de realizarse dentro de un plazo no mayor a 5 días hábiles contados a partir que se entrega el equipo al usuario, y se debe de presentar el equipo en buen estado con caja y accesorios completos.</li>
              <li><strong>•</strong>	La devolución por inconformidad solo se podrá realizar por un equipo de precio igual o mayor, en este último caso el usuario deberá de pagar la diferencia.</li>
              <li><strong>•</strong>	Solo se realizará la devolución monetaria si no se ha activado la SIM y si no se ha ingresado la tarjeta raspable de saldo.</li>
              <li><strong>•</strong>	El tiempo de la devolución a tarjeta de débito/crédito del consumo realizado será en el plazo de 15 días, dependerá de la entidad bancaria correspondiente.</li>
              <li><strong>•</strong>	Para realizar procesos de devolución monetaria o inconformidad se podrá acudir a cualquier agencia Gummybears del país.</li>
            </ul>
          </li>
        </ul>
        <p><strong>xii. Reclamos:</strong>En caso de existir reclamaciones relacionadas con la compra de productos y servicios realizada a través del sitio web uat-gummybears.com, las mismas deberán ser canalizadas a través de los medios de comunicación y divulgación de Gummybears, pudiendo  llamar al *85 o +503 2250-5555.</p>
        <h2>C. LIMITACIONES DEL SERVICIO</h2>
        <h3>i. Alcance de los servicios uat-gummybears.com</h3>
        <p>Este acuerdo no crea ningún contrato de sociedad, de mandato, de franquicia, o relación laboral entre Gummybears y el Usuario.</p>
        <p>No está permitida acción alguna o uso de dispositivo, software, u otro medio tendiente a interferir tanto en las actividades y operación de uat-gummybears.com como en las ofertas, descripciones, cuentas o bases de datos de uat-gummybears.com. Cualquier intromisión, tentativa o actividad violatoria o contraria a las leyes sobre derecho de propiedad industrial o de derechos de autor y/o a las prohibiciones estipuladas en este contrato, podrá encuadrarse en tipo penal.</p>
        <h3>ii. Fallas en el sistema</h3>
        <p>El sitio web: uat-gummybears.com no será responsable por cualquier virus que pudiera infectar el equipo del Usuario como consecuencia del acceso, uso o examen de su sitio web o a raíz de cualquier transferencia de datos, archivos, imágenes, textos, o audio contenidos en el mismo. Los Usuarios NO podrán imputarle responsabilidad alguna ni exigir pago por lucro cesante, en virtud de perjuicios resultantes de dificultades técnicas o fallas en Internet. El sistema puede eventualmente no estar disponible debido a fallas de Internet, o por cualquier otra circunstancia ajena a uat-gummybears.com; en tales casos se procurará restablecerlo con la mayor celeridad posible sin que por ello pueda imputársele algún tipo de responsabilidad.</p>
        <h3>iii. LIMITACIÓN DE RESPONSABILIDAD</h3>
        <p>POR MEDIO DE ESTA ADVERTENCIA, “Gummybears”, SUS SUBSIDIARIAS Y/O AFILIADAS, INFORMAN A LOS USUARIOS DE LAS PÁGINAS DE Gummybears, QUE A TRAVÉS DE ÉSTAS PONE A SU DISPOSICIÓN DISPOSITIVOS TÉCNICOS DE ENLACE (TALES COMO, ENTRE OTROS, LINKS, BANNERS, BOTONES), DIRECTORIOS Y HERRAMIENTAS DE BÚSQUEDA QUE LES PERMITEN ACCEDER A PÁGINAS WEB PERTENECIENTES A TERCEROS (EN ADELANTE LOS "SITIOS ENLAZADOS"). LA INSTALACIÓN DE ESTOS ENLACES EN LAS PÁGINAS DE Gummybears, SUS SUBSIDIARIAS Y/O AFILIADAS SE LIMITA A FACILITAR A LOS USUARIOS LA BÚSQUEDA DE, Y ACCESO, A LA INFORMACIÓN DISPONIBLE DE LOS SITIOS ENLAZADOS EN INTERNET, Y NO PRESUPONE QUE EXISTA NINGUNA CLASE DE VÍNCULO O ASOCIACIÓN ENTRE Gummybears, SUS SUBSIDIARIAS Y/O AFILIADAS, Y LOS OPERADORES DE LOS SITIOS ENLAZADOS.</p>
        <p>Gummybears, SUS SUBSIDIARIAS Y/O AFILIADAS NO CONTROLAN, APRUEBAN NI HACEN PROPIOS LOS SERVICIOS, INFORMACIÓN, DATOS, ARCHIVOS, PRODUCTOS Y CUALQUIER CLASE DE MATERIAL EXISTENTE EN LOS SITIOS ENLAZADOS. EL USUARIO, POR LO TANTO, DEBE EXTREMAR LA PRUDENCIA EN LA VALORACIÓN Y UTILIZACIÓN DE LOS SERVICIOS, INFORMACIÓN, DATOS, ARCHIVOS, PRODUCTOS Y CUALQUIER CLASE DE MATERIAL EXISTENTE EN LOS SITIOS ENLAZADOS.</p>
        <p>Gummybears, SUS SUBSIDIARIAS Y/O AFILIADAS, NO GARANTIZAN NI ASUMEN RESPONSABILIDAD ALGUNA POR LOS DAÑOS Y PERJUICIOS DE TODA CLASE QUE PUEDAN CAUSARSE POR:</p>
        <ul className="static--conditions">
          <li>A) EL FUNCIONAMIENTO, DISPONIBILIDAD, ACCESIBILIDAD O CONTINUIDAD DE LOS SITIOS ENLAZADOS.</li>
          <li>B) EL MANTENIMIENTO DE LOS SERVICIOS, INFORMACIÓN, DATOS, ARCHIVOS, PRODUCTOS Y CUALQUIER CLASE DE MATERIAL EXISTENTE EN LOS SITIOS ENLAZADOS.</li>
          <li>C) LAS OBLIGACIONES Y OFERTAS EXISTENTES EN LOS SITIOS ENLAZADOS.</li>
        </ul>
        <h3>iv. UTILIDAD</h3>
        <p>MEDIANTE LA UTILIZACIÓN DE ESTA PÁGINA, EL USUARIO RECONOCE Y ACEPTA QUE Gummybears, SUS SUBSIDIARIAS Y/O AFILIADAS, NO GARANTIZAN QUE LOS SITIOS ENLAZADOS O LA INFORMACIÓN PROPORCIONADA POR TERCEROS, SEAN ÚTILES PARA LA REALIZACIÓN DE NINGUNA ACTIVIDAD EN PARTICULAR</p>
        <p>MEDIANTE EL USO DE ESTA PÁGINA, EL USUARIO RECONOCE Y ACEPTA QUE Gummybears, SUS SUBSIDIARIAS Y/O AFILIADAS QUEDAN EXCLUIDAS DE CUALQUIER RESPONSABILIDAD POR LOS DAÑOS Y PERJUICIOS QUE PUDIERAN HABER SIDO CAUSADOS POR LA VERACIDAD DE LA INFORMACIÓN O CALIDAD DE SERVICIOS CONTENIDOS U OFRECIDOS POR TERCEROS O QUE SE ENCUENTRE EN LOS SITIOS ENLAZADOS, O LOS QUE SURJAN CON RELACIÓN A ESTE SITIO. TANTO EL ACCESO A ESTA PÁGINA COMO EL USO QUE PUEDA HACERSE DE LA INFORMACIÓN CONTENIDA EN EL MISMO SON EXCLUSIVA RESPONSABILIDAD DEL USUARIO.</p>
        <h3>v. SEGURIDAD</h3>
        <p>MEDIANTE EL USO DE ESTA PÁGINA, EL USUARIO RECONOCE Y ACEPTA QUE Gummybears, SUS SUBSIDIARIAS Y/O AFILIADAS, NO GARANTIZAN LA SEGURIDAD DE LOS SITIOS ENLAZADOS, Y EN PARTICULAR, QUE LOS USUARIOS PUEDAN EFECTIVAMENTE ACCEDER A LAS DISTINTAS PÁGINAS WEB QUE REPRESENTAN LOS SITIOS ENLAZADOS, NI QUE A TRAVÉS DE ÉSTOS PUEDAN TRANSMITIR, DIFUNDIR, ALMACENAR O PONER A DISPOSICIÓN DE TERCEROS SU CONTENIDO.</p>
        <p>MEDIANTE EL USO DE ESTA PÁGINA, EL USUARIO RECONOCE Y ACEPTA QUE Gummybears, SUS SUBSIDIARIAS Y/O AFILIADAS, QUEDAN EXCLUIDAS DE CUALQUIER RESPONSABILIDAD POR LOS DAÑOS Y PERJUICIOS DE TODA NATURALEZA QUE PUDIERAN SER CAUSADOS POR LA FALTA DE SEGURIDAD DE LOS SITIOS ENLAZADOS</p>
        <h3>vi. CALIDAD</h3>
        <p>MEDIANTE EL USO DE ESTA PÁGINA, EL USUARIO RECONOCE Y ACEPTA QUE Gummybears, SUS SUBSIDIARIAS Y/O AFILIADAS, NO CONTROLAN Y NO GARANTIZAN LA AUSENCIA DE VIRUS EN EL CONTENIDO DE LOS SITIOS ENLAZADOS, NI LA AUSENCIA DE OTROS ELEMENTOS QUE PUDIERAN PRODUCIR ALTERACIONES EN SUS SISTEMAS INFORMÁTICOS O EN LOS DOCUMENTOS ELECTRÓNICOS Y ARCHIVOS ALMACENADOS EN SUS SISTEMAS INFORMÁTICOS.</p>
        <h3>vii. PROPIEDAD INTELECTUAL</h3>
        <p>MEDIANTE EL USO DE ESTA PÁGINA, EL USUARIO RECONOCE Y ACEPTA QUE Gummybears, SUS SUBSIDIARIAS Y/O AFILIADAS, QUEDAN EXCLUIDAS DE CUALQUIER RESPONSABILIDAD QUE PUDIERA SER CAUSADA POR EL USO NO AUTORIZADO DE LAS MARCAS U OTROS DERECHOS DE PROPIEDAD INTELECTUAL DE TERCEROS O CONTENIDOS EN LOS SITIOS ENLAZADOS. DE IGUAL MANERA, LAS EVENTUALES REFERENCIAS QUE SE HAGAN EN ESTA PÁGINA A CUALQUIER PRODUCTO, SERVICIO, PROCESO, SITIO ENLAZADO, HIPERTEXTO O CUALQUIER OTRA INFORMACIÓN EN LA QUE SE UTILICEN MARCAS, SIGNOS DISTINTIVOS Y/O DOMINIOS, EL NOMBRE COMERCIAL O EL NOMBRE DEL FABRICANTE, SUMINISTRADOR, ETC., QUE SEAN TITULARIDAD DE TERCEROS, EN NINGÚN MOMENTO CONSTITUIRÁN, NI IMPLICARÁN RESPALDO O RECOMENDACIÓN ALGUNA POR PARTE DE Gummybears A, SUS SUBSIDIARIAS Y/O AFILIADAS Y EN NINGÚN CASO Gummybears , SUS SUBSIDIARIAS Y/O AFILIADAS SE ASIGNAN PROPIEDAD NI RESPONSABILIDAD SOBRE LOS MISMOS.</p>
        <h3>viii. ELEMENTOS DE LAS PÁGINAS</h3>
        <p>ES PROBABLE QUE, PARA PROPORCIONAR LA INFORMACIÓN CONTENIDA EN LA PÁGINA WEB TAL COMO DIBUJOS, DISEÑOS, SONIDO, VIDEOS, TEXTOS, FOTOGRAFÍAS, ETC., Gummybears, SUS SUBSIDIARIAS Y/O AFILIADAS, HUBIEREN CONTRATADO A TERCEROS PARA REALIZAR LOS ESTUDIOS E INVESTIGACIONES CORRESPONDIENTES, ASÍ COMO LOS DIBUJOS, DISEÑOS, SONIDOS, VIDEOS, TEXTOS, O FOTOGRAFÍAS, QUE SE MUESTREN EN LA PÁGINA. Gummybears, SUS SUBSIDIARIAS Y/O AFILIADAS, ADVIERTEN QUE AL NO SER DE SU TITULARIDAD, NI DESARROLLO TODA LA INFORMACIÓN CONTENIDA EN LA PÁGINA WEB, ALGUNOS DE LOS TEXTOS, GRÁFICOS, VÍNCULOS Y/O EL CONTENIDO DE ALGUNOS ARTÍCULOS INCLUIDOS EN LA MISMA, PODRÍAN NO SER VERACES O NO ESTAR ACTUALIZADOS, POR LO QUE Gummybears, SUS SUBSIDIARIAS Y/O AFILIADAS, NO SE HACEN RESPONSABLES.</p>
        <h3>ix. LEY APLICABLE Y JURISDICCIÓN</h3>
        <p>EL USUARIO AL HACER USO DE LAS PÁGINAS EN INTERNET DE Gummybears, SUS SUBSIDIARIAS Y/O AFILIADAS, ACEPTA DE MANERA EXPRESA, QUE TODAS LAS CONTROVERSIAS QUE SURJAN POR EL USO DE ESTA PAGINA Y LOS SERVICIOS QUE AQUÍ SE OFRECEN Y PROMOCIONAN SE RESOLVERÁN AMIGABLEMENTE ENTRE LAS PARTES, Y EN CASO DE NO EXISTIR ARREGLO, LAS CONTROVERSIAS SE DILUCIDARAN ANTE LA JURISDICCION DE LOS TRIBUNALES DEL DOMICILIO DE LA PARTE QUE SEA DEMANDADA.</p>
        <h2>--- – POLÍTICAS DE PRIVACIDAD</h2>
        <p>CTE, S.A. DE C.V. (EN ADELANTE “Gummybears”) se compromete a proteger la privacidad del usuario en las páginas de Gummybears y a facilitar la tecnología de desarrollo necesaria para BRINDAR INFORMACIÓN A LOS USUARIOS DE LAS PÁGINAS DE Gummybears, (EN ADELANTE LOS “USUARIOS”) para que éstos puedan disfrutar de una conexión segura y eficaz. La presente Política de Privacidad se aplica a los sitios Web de Gummybears Y SUS SUBSIDIARIAS Y/O AFILIADAS y contempla la recopilación y el uso de datos y servicios en dichos sitios. Al obtener acceso a los sitios Web de Gummybears Y SUS SUBSIDIARIAS Y/O AFILIADAS, el usuario manifiesta su consentimiento con el tratamiento de los datos a que se refiere esta declaración. Lea las presentes Políticas de Privacidad de Gummybears Y SUS SUBSIDIARIAS Y/O AFILIADAS en su totalidad, pues mediante éstas se hace constar que su información personal será mantenida en confidencialidad y que Usted, el Usuario, está de acuerdo con el manejo de la misma.</p>
        <h4 style={h4Underline}>Recopilación de Información Personal.</h4>
        <p>En algunos sitios Web de Gummybears Y SUS SUBSIDIARIAS Y/O AFILIADAS se recopila información personal que identifica al usuario que la proporciona, tal como dirección de correo electrónico, nombre del usuario, número celular, domicilio particular o de trabajo, NUMERO DE IDENTIFICACION TRIBUTARIA –NIT–, edad, sexo, intereses, preferencias y toda aquella información que Gummybears Y SUS SUBSIDIARIAS Y/O AFILIADAS consideren necesaria para estar en posibilidad de ofrecer un mejor servicio. Gummybears Y SUS SUBSIDIARIAS Y/O AFILIADAS pueden recopilar de forma automática información sobre el hardware y el software de su equipo. Entre los diversos datos que pueden ser recopilados, se encuentran la dirección IP, tipo de explorador, nombres de dominio, tiempo de acceso y direcciones de sitios Web visitados. Gummybears Y SUS SUBSIDIARIAS Y/O AFILIADAS utilizarán dicha información para administrar el servicio que ofrece a sus usuarios, para mantener la calidad de dicho servicio y obtener estadísticas genéricas relativas al uso de los sitios Web de Gummybears Y SUS SUBSIDIARIAS Y/O AFILIADAS. </p>
        <h4 style={h4Underline}>Uso de Información Personal.</h4>
        <p>La información personal recopilada por Gummybears será administrada y utilizada para prestar a los usuarios los servicios que ofrece Gummybears y que aquellos soliciten. Asimismo, los sitios de Gummybears harán uso de los datos personales del usuario para informar a este sobre los productos y servicios disponibles. Gummybears no podrá enajenar ni arrendar a terceros SUS BASES DE DATOS de usuarios. Sin embargo, en determinadas ocasiones Gummybears podrá contactar a los usuarios en nombre de ciertos sitios Web relacionados con Gummybears para informarles sobre el lanzamiento de ofertas que pudieran ser de su interés conforme lo establecido en la legislación aplicable. En dicho supuesto, la información personal del usuario por ningún motivo será proporcionada a terceros. Asimismo, Gummybears vigila y da seguimiento a los sitios y páginas Web visitados por sus usuarios para determinar cuáles son los sitios y servicios de Gummybears más populares. De esta manera, puede enviarse a los usuarios de Gummybears información y publicidad en forma personalizada, en función de sus intereses específicos, conforme lo establecido en la legislación aplicable. Gummybears podrán revelar información personal de sus usuarios única y exclusivamente en los siguientes casos: (a) En cumplimiento de alguna orden emitida por autoridad judicial competente, (b) Cuando ello sea indispensable para proteger y defender los derechos de propiedad intelectual de Gummybears Y/O DESUS SUBSIDIARIAS Y/O AFILIADAS, del sitio o de los usuarios de Gummybears, y (c) Actuando bajo circunstancias excepcionales para proteger la seguridad personal de los usuarios de Gummybears.</p>
        <h4 style={h4Underline}>Seguridad de Información Personal.</h4>
        <p>Gummybears está comprometida a proteger la Información Personal que sus usuarios comparten, por lo que utiliza procedimientos físicos, electrónicos y de gestión estándar para evitar el acceso, uso o divulgación no autorizada. Cuando se transfiere Información Personal a través de Internet, Gummybears utiliza encriptación SSL.</p>
        <p>Si bien existe un esfuerzo para proteger la Información Personal, no se puede asegurar la seguridad de la información que los usuarios de Gummybears proporcionan a través de una conexión de Internet no segura. Por este motivo, el Usuario debe tomar todas las medidas necesarias para proteger la Información Personal cuando está en Internet, quedando esta protección bajo su entera responsabilidad. Asimismo, el Usuario debe estar consciente de los ataques de “Phishing”, a través de los cuales se intenta robar Información Personal de los consumidores. Los “phishers” utilizan correos electrónicos para llevar al consumidor a sitios web falsos, diseñados para engañar al destinatario y que éste proporcione Información Personal Sensible, tal como números de tarjeta de crédito, nombre de usuario de una cuenta, contraseñas y números de identificación personal. Gummybears nunca le enviará un correo electrónico, pidiéndole que proporcione o confirme Información Personal sensible. Si recibe una comunicación como las mencionadas, por favor reenvíela a abuse@Gummybears.com.sv y bórrela inmediatamente de su ordenador.</p>
        <h4 style={h4Underline}>Uso de los cookies.</h4>
        <p>Gummybears puede utilizar cookies para facilitar la personalización de la experiencia en línea del usuario. Un cookie es un archivo de texto situado por un servidor de páginas Web en el disco duro. Los cookies no se pueden utilizar para ejecutar programas o transmitir virus al equipo del usuario; únicamente se asignan al usuario y sólo puede leerlos un servidor Web que pertenezca al dominio que lo emitió. Una de las principales funciones de los cookies es el ahorro de tiempo. Los cookies se encargan de informar al servidor Web que el usuario ha vuelto a una página determinada. El usuario podrá aceptar o rechazar los cookies. La mayor parte de los exploradores Web aceptan automáticamente los cookies. No obstante lo anterior, el usuario puede modificar el explorador para rechazarlos. Si este es el caso, probablemente el usuario no pueda hacer uso de todas las características interactivas de los servicios que Gummybears Y SUS SUBSIDIARIAS Y/O AFILIADAS pueden ofrecer.</p>
        <h4 style={h4Underline}>Privacidad de Menores.</h4>
        <p>El Usuario debe tener al menos 18 años de edad para acceder y hacer uso a los sitios y páginas Web de Gummybears Y SUS SUBSIDIARIAS Y/O AFILIADAS, las cuales no recabarán ni comercializarán intencionalmente información personal en línea de personas menores de 13 años de edad. Si llega a ser del conocimiento de Gummybears Y SUS SUBSIDIARIAS Y/O AFILIADAS que un menor de 13 años les ha proporcionado información personal, se tomarán las medidas necesarias para eliminar dicha información y dar por terminada la cuenta del menor de forma automática.</p>
        <h4 style={h4Underline}>Configuraciones de Privacidad.</h4>
        <p>Si el usuario ya no desea: (1) recibir ofertas de comercialización y/o promoción de los productos y servicios de Gummybears, o de aquellos que puedan ser de su interés; o (2) que Gummybears comparta su información personal con terceros con fines de comercialización como se establece en esta Política de Privacidad, puede llamar al *85 o +503 2250-5555 e indicar el medio de contacto que quiere eliminar. Tome en cuenta que no puede eliminar la suscripción de cierta correspondencia relacionada con nuestros servicios, incluyendo mensajes relativos a las operaciones de su cuenta. Independientemente de las elecciones que realice para comunicaciones de promoción y actualizaciones referentes a contenido, podemos enviarle mensajes administrativos, anuncios del servicio, términos y condiciones de su cuenta o comunicaciones similares, conforme lo establecido en la legislación aplicable.</p>
        <h4 style={h4Underline}>Modificaciones a la Política de Privacidad.</h4>
        <p>Gummybears Y SUS SUBSIDIARIAS Y/O AFILIADAS se reservan el derecho de modificar en cualquier momento las presentes políticas. Las modificaciones que en su caso se efectúen se harán del conocimiento de los usuarios en las páginas y sitios Web de Gummybears Y SUS SUBSIDIARIAS Y/O AFILIADAS.</p>
        <aside>
          <h2>--- – POLITICAS PARA GARANTÍA DE FABRICA </h2>
          <h5>CTE, S.A. DE C.V. (EN ADELANTE “Gummybears”) AGRADECE SU CONFIANZA Y PREFERENCIA AL ADQUIRIR SUS EQUIPOS POR MEDIO DE Gummybears Y ESPERA QUE ESTÉ SATISFECHO DE SU COMPRA.</h5>
          <p>Al realizar la compra de equipos terminales en Gummybears, EL USUARIO COMPRADOR acepta conforme que los Términos y Condiciones se aplicarán desde el momento en que compra el equipo en Gummybears y acepta las condiciones que el Fabricante ofrece como Garantía Limitada, siendo las siguientes:</p>
          <p>Los equipos terminales tendrán una garantía de fabricante de trescientos sesenta y cinco (365) días calendario a partir de la fecha de compra o activación de parte del usuario.</p>
          <p>En el caso que el equipo adquirido por EL USUARIO presente fallas o desperfectos de fábrica, dentro de los primeros siete (7) días calendario posteriores a la venta, éste puede reclamar el reemplazo del mismo con base en la garantía de fábrica, en las agencias Gummybears detalladas previamente en este documento o al Fabricante, a este último a través del Centro de Servicio Autorizado por el Fabricante, siempre que se cumplan las condiciones siguientes:</p>
          <ul>
            <li>a. Que el equipo que presente fallas dentro de los primeros siete (7) días calendario a partir de la fecha de compra, no haya sido objeto de manipulación negligente o mal uso contrario a las instrucciones del Fabricante para el uso y mantenimiento del mismo;</li>
            <li>b. Tener un defecto de fábrica. El equipo no debe presentar indicios de mal uso como golpes, arañazos, rayones en marcas, rozaduras, humedad, etc. Esté deberá ser devuelto en su caja original de la marca entregada,  y con los accesorios que le fueron entregados al momento de la contratación intactos en buen estado;</li>
            <li>c. Presentar copia de la factura de compra (o comprobante), expedida al usuario final, en la fecha de venta. El código de identidad internacional de equipo móvil (IMEI, del inglés International Mobile Equipment Identity) del terminal debe ser el mismo que figura en la factura o comprobante que se le entregó;</li>
            <li>d. Que la etiqueta del número electrónico de servicios (ESN del inglés Electrical Service Number) / IMEI del equipo estén claras, no dañadas ni alteradas, así como la etiqueta en las cajas de embalaje (ESN, IMEI), ya que éstas respaldan que el número de serie de la caja, sea el mismo número de serie de los equipos.</li>
          </ul>
          <p>En caso de haber transcurrido los siete (7) días calendario, o si el equipo no cumple con las condiciones para reclamo de cambio por fallas o desperfectos de fábrica dentro de los primeros 7 días antes mencionados, el equipo aplica a revisión y/o reparación dentro de la garantía limitada del producto otorgada por el Fabricante, ingresando  el terminal a revisión técnica en agencias de Gummybears o en las instalaciones del centro de servicio autorizado por el fabricante,  cuyos términos son los siguientes:</p>
          <h4>Términos Garantía Limitada del Equipo:</h4>
          <p>El Fabricante brindará el soporte técnico y/o el servicio de garantía indicada en este documento a partir del día ocho (8) o incluso desde el día de la compra. Con esta garantía, el Fabricante garantiza el producto contra posibles defectos relacionados con el material y mano de obra, durante el período de trescientos sesenta y cinco (365) días contados a partir de la fecha de la compra. Para tales efectos, el USUARIO deberá reportar sus reclamos por defectos en el EQUIPO, cubiertos por la garantía del fabricante, a su discreción, en agencias propias de Gummybears o al fabricante.</p>
          <p>Si durante este período de garantía el producto tuviera defectos de fábrica, el Fabricante reparará o reemplazará a su entera discreción el equipo o sus piezas defectuosas, en las condiciones que se especifican a continuación y sin ningún cargo por mano de obra o piezas:</p>
          <ul>
            <li><strong>1. La garantía aplicará cuando las fallas que presente el equipo  tengan su origen en defectos de fábrica, es decir por causas no imputables al usuario comprador.</strong></li>
            <li><strong>2. El equipo a cambiar, deberá estar en perfecto estado físico, como mínimo el usuariocomprador deberá entregar, batería, teléfono y cover.</strong></li>
            <li><strong>3. Exista disponibilidad de stock de marca y modelo igual al del usuario comprador, de lo contrario se dará otro equivalente de la misma marca o de características similares.</strong></li>
          </ul>
          <p>Los accesorios solo tienen 6 meses de garantía, esto incluye cargador, batería y manos libres (si incluyera).Todas las reclamaciones deben ser enviadas por escrito a DHL y recibidas por ésta en un plazo de treinta (30) días a partir de la fecha en que DHL aceptó el Envío, a falta de lo cual DHL quedará eximida de toda responsabilidad.</p>
          <h4>Exclusión de Garantía:</h4>
          <p>Quedan expresamente excluidos de garantía de fábrica, los equipos y accesorios que presenten alguna falla o avería relacionada con alguna de las siguientes circunstancias:</p>
          <ul>
            <li>i. Cuando el equipo o accesorio presente defectos o daños derivados del uso anormal de éste, o uso contrario al indicado en el manual de operación (Guía del Usuario) que le acompaña. Se recomienda la lectura del manual de usuario.</li>
            <li>ii. Cuando el fabricante o taller de Gummybears determine que, el equipo o accesorio presenta defectos o daños derivados de pruebas, operación, mantenimiento, instalación o ajustes inapropiados o derivados de cualquier alteración o modificación realizada por el usuario o por centros de servicio técnico ajenos al de Gummybears.</li>
            <li>iii. Cuando el fabricante o taller de Gummybears determine que, el equipo o accesorio presenta defectos o daños derivados de accidente o negligencia, golpes (hendidura), expuestos a descargas eléctricas, calor o evidencias de residuos líquidos o humedad.</li>
            <li>iv. Cuando el fabricante o taller de Gummybears determine y compruebe que, las condiciones ambientales donde ha sido utilizado el equipo, no cumplen con las exigencias respecto de temperatura, humedad, polvo, vibraciones, entre otras de similares características avaladas por el Fabricante.</li>
            <li>v. Cuando el equipo presente alguna alteración en el número de serie o cuando el mismo sea ilegible.</li>
            <li>vi. Cuando los cables de la unidad de control hayan sido cortados o tengan rotos algunos de sus conectores o terminales.</li>
            <li>vii. Cuando el equipo haya sido utilizado con accesorios no originales.</li>
            <li>viii. Cuando las baterías sean cargadas por cualquier otro cargador que no sea el original.</li>
            <li>ix. Cuando cualquiera de los sellos de las baterías y/o equipos se encuentre roto o modificado o presente señales de activación por humedad.</li>
            <li>x. Cuando las baterías hayan sido usadas o instaladas en un equipo distinto al del equipo al que corresponde.</li>
            <li>xi. Cuando el fabricante o taller de Gummybears determine que, el equipo presenta alteraciones en el software y que estas hayan sido realizadas por el usuario o por terceros no autorizados.</li>
          </ul>
          <h5>PARA LOS EQUIPOS MARCA APPLE (IPHONE), LOS TÉRMINOS Y CONDICIONES APLICABLES A LA GARANTÍA DE FÁBRICA SON LOS SIGUIENTES:</h5>
          <p>Al realizar la compra de un equipo IPhone, en Gummybears, EL USUARIO acepta conforme que los presentes Términos y Condiciones aplicables a la Garantía del Fabricante, se aplicarán desde el momento de la compra del mismo en Gummybears, y acepta las condiciones que el Fabricante ofrece como Garantía Limitada, siendo éstas las siguientes:</p>
          <h4>Términos Garantía Limitada del Equipo:</h4>
          <p>El Fabricante brindará el soporte técnico y/o el servicio de garantía indicada en este documento a partir del día de la compra. El usuario comprador puede hacer el ingreso de su terminal a revisión técnica en Agencias de Gummybears o en las instalaciones del centro de servicio autorizado por el fabricante.</p>
          <p>Si durante este período de garantía el equipo o terminal tuviera defectos de fábrica, el Fabricante reparará o reemplazará a su entera discreción el equipo o terminal, o sus piezas defectuosas.</p>
          <p>La garantía aplicará cuando las fallas que presente el equipo o terminal tengan su origen en defectos de fábrica, es decir por causas no imputables al usuario comprador.</p>
          <p>Cuando, derivado de la aplicación de la garantía, el centro de servicio iShop realice un reemplazo de equipo, el usuario deberá presentarse a cualquier agencia de Gummybears para registrar el nuevo IMEI proporcionado por el Fabricante, en los sistemas de Gummybears. Todas las reclamaciones deben ser enviadas por escrito a DHL y recibidas por ésta en un plazo de treinta (30) días a partir de la fecha en que DHL aceptó el Envío, a falta de lo cual DHL quedará eximida de toda responsabilidad.</p>
          <h4>Exclusión de Garantía:</h4>
          <p><strong>Quedan expresamente excluidos de la garantía de fábrica</strong>, los terminales y accesorios que presenten alguna falla o avería relacionada con alguna de las siguientes circunstancias: </p>
          <ul>
            <li>i. Cuando el terminal o accesorio presente defectos o daños derivados del uso anormal de éste, o uso contrario al indicado en el manual de operación (Guía del Usuario) que le acompaña. Se recomienda la lectura del manual de usuario.</li>
            <li>ii. Cuando el fabricante o Centro de Servicio iShop determine que el terminal o accesorio presenta defectos o daños derivados de pruebas, operación, mantenimiento, instalación o ajustes inapropiados o derivados de cualquier alteración o modificación realizada por el usuario o por centros de servicio técnico ajenos a Gummybears o al Centro de Servicio iShop.</li>
            <li>iii. Cuando el fabricante o Centro de Servicio iShop determine que el terminal o accesorio presenta defectos o daños derivados de accidente o negligencia, golpes (hendidura), expuestos a descargas eléctricas, calor o evidencias de residuos líquidos o humedad.</li>
            <li>iv. Cuando el fabricante o Centro de Servicio iShop determine y compruebe que las condiciones ambientales donde ha sido utilizado el terminal, no cumplen con las exigencias respecto de temperatura, humedad, polvo, vibraciones, entre otras de similares características avaladas por el Fabricante.</li>
            <li>v. Cuando el terminal presente alguna alteración en el número de serie o cuando el mismo sea ilegible.</li>
            <li>vi. Cuando los cables de la unidad de control hayan sido cortados o tengan rotos algunos de sus conectores o terminales.</li>
            <li>vii. Cuando el terminal haya sido utilizado con accesorios no originales.</li>
            <li>viii. Cuando las baterías sean cargadas por cualquier otro cargador que no sea el original.</li>
            <li>ix. Cuando cualquiera de los sellos del terminal se encuentre rotos o modificados o presente señales de activación por humedad.</li>
            <li>x. Cuando la batería haya sido usada o instalada en un terminal distinto al del terminal al que corresponde.</li>
            <li>xi. Cuando el fabricante o Centro de Servicio iShop determine que el terminal presenta alteraciones en el software y que estas han sido realizadas por el usuario o por terceros no autorizados.</li>
            <li>xii. El diagnóstico y/o mantenimiento a nivel de software no es cubierto por la garantía.</li>
          </ul>
          <p>Para equipos o terminales no cubiertos por garantía, el centro de servicio iShop podrá ofrecer piezas de reemplazo, dependiendo del caso y de la antigüedad, previo diagnóstico, lo cual será sometido a consideración del USUARIO, quien deberá asumir el costo de las piezas a reemplazar.</p>
        </aside>
      </section>
    </main>
  );
};

export default Terms;
